language: java
jdk: oraclejdk8
before_install:
- wget -O codacy-coverage-reporter.jar http://central.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.10/codacy-coverage-reporter-1.0.10-assembly.jar
script:
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn test ; fi
after_success:
- mvn clean verify
- java -jar codacy-coverage-reporter.jar -l Java -r ./target/site/jacoco/jacoco.xml
- mvn coveralls:report
notifications:
  email: false
env:
  global:
  - secure: ULqIle4S3jZjnhs7qtsY16cdDRqNbQvVmaKrqa6CAIPAqUadFV6+59rT5iZrloaNNbo5zukiynTl/zeIsICRrHEhiflsG7PEZ5Y1CY/1ZI7UdodlWvNC2aj6TIjVKiR/nb4APi1DqIOzoJxPw+RVTnwdYe41s/mZerHdG87WF04qaYqEwaURmUmi95LReIFtUaZ4bY9CorcAFjzJTVRk6vhhj/Zadmzs6c0T3fvqDvqiDNkI9IiJBaHtUwd6MfCBdsCwSZ7ziEoiajIxekePe4hEz3FlL9XhC0Uaa+/FhVae7fL6261HCQLlaV/iUbp/88gUIYt7q/OlMNeDQ5HVj96NcHHstgBrJwG4xeQy8TkoCaxYL8IiNjzeWjRllpJkhkT1Pd4QG2zxKbYjCOAQ7TYbUWWQcOaL3kyTio8+ow52psDyxh1XPFenz9IUtBR/wK4XsTg9n8THblpNmqyl1F9jOg0VHh3x5dI5BXpx/KbRcuQmSENFw87SoxVGKsmqNqWJlFS3Q4zWIqtHjmjQ+rJRFE7l8pglCHiWWcz7D6G6Bq7eI2MTyuRBsW0AycYYroDG8u9Yovw7TfqbSF/cnc7PZrXJj7Zayryfd0UnQfZVh1ihOklTifJB59M37KKw+wJi/95WhkVYdNnRUgRaN60U2lb2Va8QifRy8OW1cFY=
  - secure: TYWEKlEo3x/y3bB8yNIMxndyQhgTyk6eRDS1ABWrcPgxUk9gfiy0OxM9iDeOMmLym0RGlQNRDNtTOjTXsysRoMC3EM+qAjH6aufptFN5XpDbfJYxntGMQaxnCAY2uiB0+edtbGton8CvBOGI/gRFD4H8OwKOMBN0pe1GbN1rigMi6eYtqhb2tnEwY5jxFi5p8OAOd3JScPSk3Iz5nNsEY+Q5iTl05ikQFMNpqREvE2aB6IEdQkjo8BPwTPvo3ptTYYm7aCIZ7V83NBgZH/i7WbgexW53mO6l0Qmv3Q+dvwJA2o/WVABXyd9ssXAGdumqILDGN6Hk7d9/Ff47oxcI+AAV4h0bFe9jI+IEQDE25b9A4iCFoaPcdwqXVlShZmhpR0Wwm32GbFfKN0J/3oe06J3M5s5gOWy8wDjH0AXHEBT1um3Xn7RIieNOjrmFN20WBr6OgrOI4lLTm9djlFSTvFv5gCpFpx+ld78Z+BjpDq1SSlC4hRC7a1kyY1MJyk6FGM4UINVG52YN40h2XjQWOkTZdy7OshTyKFfbNijuj2v/7JmM70w+1fY6bkYhTlx8xlCjZ13LbXLX3dRfxqmwzQY+kyBCcm32Ky6UikfKbb/ZBwC28GStbGPj5IY5i1zgXDiBZZ65tZGbYg3HUH+rDoTl7VA1LixJxRG8LgFSBo4=
addons:
  coverity_scan:
    project:
      name: barrycommins/simple-rest-ci-cd-demo
      description: Build submitted via Travis CI
    notification_email: builds@barrycommins.com
    build_command_prepend: mvn clean
    build_command: mvn test verify
    branch_pattern: master
