language: java
jdk: oraclejdk8
edge: true
before_install:
- wget -O codacy-coverage-reporter.jar http://central.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.10/codacy-coverage-reporter-1.0.10-assembly.jar
script:
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn verify ; fi
after_success:
- java -jar codacy-coverage-reporter.jar -l Java -r ./target/site/jacoco/jacoco.xml
- mvn coveralls:report
notifications:
  email: false
env:
  global:
  - secure: ULqIle4S3jZjnhs7qtsY16cdDRqNbQvVmaKrqa6CAIPAqUadFV6+59rT5iZrloaNNbo5zukiynTl/zeIsICRrHEhiflsG7PEZ5Y1CY/1ZI7UdodlWvNC2aj6TIjVKiR/nb4APi1DqIOzoJxPw+RVTnwdYe41s/mZerHdG87WF04qaYqEwaURmUmi95LReIFtUaZ4bY9CorcAFjzJTVRk6vhhj/Zadmzs6c0T3fvqDvqiDNkI9IiJBaHtUwd6MfCBdsCwSZ7ziEoiajIxekePe4hEz3FlL9XhC0Uaa+/FhVae7fL6261HCQLlaV/iUbp/88gUIYt7q/OlMNeDQ5HVj96NcHHstgBrJwG4xeQy8TkoCaxYL8IiNjzeWjRllpJkhkT1Pd4QG2zxKbYjCOAQ7TYbUWWQcOaL3kyTio8+ow52psDyxh1XPFenz9IUtBR/wK4XsTg9n8THblpNmqyl1F9jOg0VHh3x5dI5BXpx/KbRcuQmSENFw87SoxVGKsmqNqWJlFS3Q4zWIqtHjmjQ+rJRFE7l8pglCHiWWcz7D6G6Bq7eI2MTyuRBsW0AycYYroDG8u9Yovw7TfqbSF/cnc7PZrXJj7Zayryfd0UnQfZVh1ihOklTifJB59M37KKw+wJi/95WhkVYdNnRUgRaN60U2lb2Va8QifRy8OW1cFY=
  - secure: TYWEKlEo3x/y3bB8yNIMxndyQhgTyk6eRDS1ABWrcPgxUk9gfiy0OxM9iDeOMmLym0RGlQNRDNtTOjTXsysRoMC3EM+qAjH6aufptFN5XpDbfJYxntGMQaxnCAY2uiB0+edtbGton8CvBOGI/gRFD4H8OwKOMBN0pe1GbN1rigMi6eYtqhb2tnEwY5jxFi5p8OAOd3JScPSk3Iz5nNsEY+Q5iTl05ikQFMNpqREvE2aB6IEdQkjo8BPwTPvo3ptTYYm7aCIZ7V83NBgZH/i7WbgexW53mO6l0Qmv3Q+dvwJA2o/WVABXyd9ssXAGdumqILDGN6Hk7d9/Ff47oxcI+AAV4h0bFe9jI+IEQDE25b9A4iCFoaPcdwqXVlShZmhpR0Wwm32GbFfKN0J/3oe06J3M5s5gOWy8wDjH0AXHEBT1um3Xn7RIieNOjrmFN20WBr6OgrOI4lLTm9djlFSTvFv5gCpFpx+ld78Z+BjpDq1SSlC4hRC7a1kyY1MJyk6FGM4UINVG52YN40h2XjQWOkTZdy7OshTyKFfbNijuj2v/7JmM70w+1fY6bkYhTlx8xlCjZ13LbXLX3dRfxqmwzQY+kyBCcm32Ky6UikfKbb/ZBwC28GStbGPj5IY5i1zgXDiBZZ65tZGbYg3HUH+rDoTl7VA1LixJxRG8LgFSBo4=
addons:
  coverity_scan:
    project:
      name: barrycommins/simple-rest-ci-cd-demo
      description: Build submitted via Travis CI
    notification_email: builds@barrycommins.com
    build_command_prepend: mvn clean
    build_command: mvn verify
    branch_pattern: coverity-scan
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username:
    secure: iNnDBBYrgEMhOLxObQFKitoX7iTRFocfJQ7YENekxXnSScdT3YGCaJVidEewEorcTTPgknAWVRtwHfhZYDDL3ReZpfkViRIDpHb49qjOpHYTF9mI+9D8Gsz6VOePX/hlwnurSz5Kipiepbj/G2V/MIParU5rQ1nc1/sLT6UDYiAROXcGS6tGDzl7/+oO1AOk9rgT+GwhXWYLYR9bwf11fD+fuA9XRA5bgo62kjENGjSXDiD3DRvRvlwhgHusGdZcYCOnEd+gUVeXc229Mc/9ie5+5m/ciXMeBa0HCFKrfiGW0nUnCaxO924+JuMrC0N8qXTGqFlP/tgn2xJr7nH6FLFoesPJ/ayC1AJMP0k+uASN0Um1xLpswWeHIDqhpoNkVIJKdrr2xBCSJSNJ6HpkX0qvjxN/9/vkQ8+eXiGFrf9h6ifWeiToQ8HeqphBuRtMh+2rLiqzGYffMU5XxdSwqlE/Q70fZkcBGKRRaWE7YWuGwUzyFMiSZzpTTtQFltLDqzwbFxv9OTEPp46vV8x373fYQ+l0tTvkpvXprNQBaPZZnjPHBpj+PwFZjdGmWEPm12JhN421wpZOg2u3JKd+bwJ7sROBQwFTcmqJOyZ2gj3guOXqhc0QoQ/VY53PwIePgnMPIGMVH3K6/XLQa7+6f4kOWidBK8qvZR+f1br5j/w=
  password:
    secure: gWDuZ60kC/fLNKyERH4kylbn1ofdBVe4K3a2n7z05jcasKXkGIAkOh93x7tPCjv/YUJYeA2Tp1aZh342TyH0rFk35W74tYjdA9DO7AkxvZPM4HnNFB46gAYreehCDp5dN//iml75pAqu5t1IY/H+WQGi9wWKbexd5AjCp4g11QsK+cpykxti0NNh68gnw6wPJgp8SBhtncdx2RVvUwh34+Ghh4A/xicdB2w8I8bPglhrEc+7O3vKPOGhDP7R93MffhB4erNNkL0u3iR0ozeTpTPekd8hKZIFxJFz95yRpiMA5jTecJ1X7nDDMk2CNir/O/8t+XlbAn3yDbJeBHkbuGRluDnxCAMWeurRpsPPQ2k2nK0yR7M5QEVzATyFvu1eN8IhpwViFpX9csRiz9/dxq+jhAKmqvdFOZGvH2YzSkU3gN7qvn7KnSzVeBHJvqdcyrUxPHd8EHh31bfqBuOe/KCRinypDbGJGpnQayDvvsu5rCbFrjfkES2hJ19+HB4PJHSN/zkpIu6yt0GzpxRAbnQOaJRqekSeg6URY/oL1u8FHs0YOsedIrnT10htPWEc+h4R4wz5hJIcxbM6iYRh/OBQCho+WOuuRLcf6yFUFFD1gE+M6hUWb53v/SMPjE405C7PrD4vIe1z0ne7ZyPrUe/fHPZsRzUYORLuLmaQrxk=
  organization: barrycommins-org
  space: development
  on:
    repo: barrycommins/simple-rest-ci-cd-demo
