language: java
jdk: oraclejdk8
script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn test verify ; fi
notifications:
  email: false
env:
  global:
   - secure: "ULqIle4S3jZjnhs7qtsY16cdDRqNbQvVmaKrqa6CAIPAqUadFV6+59rT5iZrloaNNbo5zukiynTl/zeIsICRrHEhiflsG7PEZ5Y1CY/1ZI7UdodlWvNC2aj6TIjVKiR/nb4APi1DqIOzoJxPw+RVTnwdYe41s/mZerHdG87WF04qaYqEwaURmUmi95LReIFtUaZ4bY9CorcAFjzJTVRk6vhhj/Zadmzs6c0T3fvqDvqiDNkI9IiJBaHtUwd6MfCBdsCwSZ7ziEoiajIxekePe4hEz3FlL9XhC0Uaa+/FhVae7fL6261HCQLlaV/iUbp/88gUIYt7q/OlMNeDQ5HVj96NcHHstgBrJwG4xeQy8TkoCaxYL8IiNjzeWjRllpJkhkT1Pd4QG2zxKbYjCOAQ7TYbUWWQcOaL3kyTio8+ow52psDyxh1XPFenz9IUtBR/wK4XsTg9n8THblpNmqyl1F9jOg0VHh3x5dI5BXpx/KbRcuQmSENFw87SoxVGKsmqNqWJlFS3Q4zWIqtHjmjQ+rJRFE7l8pglCHiWWcz7D6G6Bq7eI2MTyuRBsW0AycYYroDG8u9Yovw7TfqbSF/cnc7PZrXJj7Zayryfd0UnQfZVh1ihOklTifJB59M37KKw+wJi/95WhkVYdNnRUgRaN60U2lb2Va8QifRy8OW1cFY="
addons:
  coverity_scan:
    project:
      name: "barrycommins/simple-rest-ci-cd-demo"
      description: "Build submitted via Travis CI"
    notification_email: builds@barrycommins.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn test verify"
    branch_pattern: coverity_scan